apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pljvvyi25-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pljvvyi25-go 
  name: pljvvyi25-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pljvvyi25-go 
